### PR TITLE
AMP Review 1

### PR DESCRIPTION
**Pull request by andrewrreed**
# Purpose

The purpose of this PR is purely to track notes / edits / suggestions while while reviewing the AMP

# Comments & Feedback

- [x] 1. We might want to change the value here from "SUPER AWESOME EIA KEY" to just "EIA KEY". I have no doubt that it is an awesome key... but maybe we can let the users find that out for themselves 😄 

https://github.com/fastforwardlabs/structural-time-series/blob/260e03cc19d72a55b385821e395570d145bc4288/.project-metadata.yaml#L11

- [x] 2. This should be "Cloudera Inc." instead of "Cloudera Engineer" (per legal team's designation)

https://github.com/fastforwardlabs/structural-time-series/blob/260e03cc19d72a55b385821e395570d145bc4288/.project-metadata.yaml#L3

- [x] 3. Minor wording blip in `README` here:
image

### CODE REVIEW

**Comment by andrewrreed** [comment]
https://github.com/fastforwardlabs/structural-time-series/blob/260e03cc19d72a55b385821e395570d145bc4288/.project-metadata.yaml#L11

**Comment by andrewrreed** [comment]
@cjwallace Review 1 for _AMP_5 Structural Time Series_ is documented [here](https://docs.google.com/document/d/1u_vg5vzYJm7wvRK6-IWFE9Xdcy3WxrqqYD1faFfTJRE/edit#). In addition to the few items noted in this PR, the only other missing pieces are source headers in the code files and a LICENSE.txt at the root of the project.

Feel free to just push commits directly to this PR as you make these few changes. Let me know if you have any questions/concerns - Thanks!

**Comment by cjwallace** [comment]
@andrewrreed Fixes applied, I think this is ready for re-review (in particular that I hit all the right places with the copyright notice).

I also applied autopep8 formatting to source files. Separate commit for easier review. I suggest we do similarly for future AMPs (we could actually enforce this in CI with github actions, though there may be times we want to consciously abandon a formatting convention). I don't have a strong opinion on one formatter over another mind, and it could vary per-project. Seems like an easy win for consistent style. (With the caveat that I did this automatically on save in vscode, and doing it from a non-vscode CML session requires running the CLI for autopep8/formatter of choice).

**Comment by andrewrreed** [comment]
Looks great - only thing I added was a copyright header to the `setup.py` file at the root of project. 

I can now fully appreciate what you meant in the last code review by separating out auto-formatting changes into a separate commit - super helpful when reviewing! I agree that we should enforce project files have _some_ type of auto-formatting applied and that it is consistent within the project. Probably isn't realistic to enforce everyone uses the same though...I'll add this as a note in the AMP Review Sheet criteria.

One other thing to note - is that for the new AMPs you're working on, be sure to update the date in the copyright header to 2021. I started updating them in this repo, but then reverted back since this project was technically developed in 2020, so it should be fine.

**Pull request merged**
